services:
  export-app:
    build: ./microservices/export  
    ports:
      - "5000:5000"
    volumes:
      - ./export-app:/microservices/export
    networks:
      - app-network
  auth-app:
    build: ./microservices/auth
    ports:
      - "5001:5001"
    volumes:
      - ./auth-app:/microservices/auth
    networks:
      - app-network
  tasks-app:
      build: ./microservices/tasks
      ports:
        - "5002:5002"
      volumes:
        - ./tasks-app:/microservices/tasks
      networks:
        - app-network
  angular-app:
    build: ./webPortal 
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge