name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: LogIn to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t export-app -f ./microservices/export/Dockerfile ./microservices/export

    - name: Run Docker Container
      run: docker run -d --name export-app -p 5000:5000 export-app

    - name: Wait for the app to start
      run: sleep 10

    - name: Test the app with curl
      run: |
        curl -f http://127.0.0.1:5000/export_tasks && echo "App is running successfully." || (echo "App did not start" && exit 1)

    - name: Stop and remove container
      run: docker stop export-app && docker rm export-app

    - name: Tag Docker image
      run: docker tag export-app:latest cruasanya/tasking

    - name: Push Docker Image to DockerHub
      run: docker push cruasanya/tasking
